config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users,
  controllers: { omniauth_callbacks: 'users/omniauth_callbacks', :registrations => "users/registrations" }

  root to: 'pages#home'

  get "/my_bookings", to: 'profiles#my_bookings'
  get "/my_requests", to: 'profiles#my_requests'
  get "/created_events", to: 'profiles#created_events'

  get '/my_profile', to: 'profiles#my_profile'
  get "my_profile/edit", to: "profiles#edit"
  patch "my_profile/", to: "profiles#update"
  get "/profile/:id", to: "profiles#show", as: "profile"

  resources :notifications, only: [:index, :destroy]

  # get "/bookings/pending_denied_show/:id", to: "bookings#pending_denied_show", as: "pending"
  get "/bookings/pending/:id", to: "bookings#pending", as: "pending"


  mount Attachinary::Engine => "/attachinary"

  resources :events do
    member do
      get :protected
    end

    resources :bookings, only: [:new, :create]
  end

  resources :chat_rooms, only: [:new, :create, :show, :index]
  mount ActionCable.server => '/cable'



  resources :bookings, except: [:new, :create]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  skip_after_action :verify_authorized

  def my_profile
    @user = current_user

    @hash = Gmaps4rails.build_markers([@user]) do |user, marker|
      marker.lat user.latitude
      marker.lng user.longitude
      # marker.infowindow render_to_string(partial: "/flats/map_box", locals: { flat: flat })
    end

  end

  def show
    @user = User.find(params[:id])

    @hash = Gmaps4rails.build_markers([@user]) do |user, marker|
      marker.lat user.latitude
      marker.lng user.longitude
      # marker.infowindow render_to_string(partial: "/flats/map_box", locals: { flat: flat })
    end
  end

  def edit
    @user = current_user

  end

  def update
    @user = current_user
    @user.update(user_params)

    if @user.save
      redirect_to my_profile_path
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :username, :bio, :photo, :address, :likes, :gender, sport_ids: [])
  end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/_created_events.html.erb
<% @user = current_user %>

<div class="container">

  <h2 class="clear-header">Your created events</h2>

  <h3>Active events</h3>


  <div class="row">
    <% if @user.events %>
      <% @user.events.where(active: true).each do |event| %>
        <div class="col-xs-12 col-sm-6 col-md-4">
          <div class="grid">
            <figure class="effect-bibi">
              <% background_image = ("sports-photos/" + event.sport.name + ".jpg") %>
              <%= image_tag (background_image) %>
              <figcaption>
                <h2> <%= event.title %> </h2>
                <p><%= event.description.truncate_words(10) %></p>
                <p><%= event.start_time %></p>
                <%= link_to "", event_path(event), class: "card-link"%>
              </figcaption>
            </figure>
          </div>
        </div>
      <% end %>
    <% else %>
    <p>No events to show</p>
    <% end %>
  </div>

    <h3>Inactive events</h3>

  <div class="row">
    <% if @user.events %>
      <% @user.events.where(active: false).each do |event| %>
        <div class="col-xs-12 col-sm-6 col-md-4">
          <div class="grid">
            <figure class="effect-bibi">
              <% background_image = ("sports-photos/" + event.sport.name + ".jpg") %>
              <%= image_tag (background_image) %>
              <figcaption>
                <h2> <%= event.title %> </h2>
                <p><%= event.description.truncate_words(10) %></p>
                <p><%= event.start_time %></p>
                <%= link_to "", event_path(event), class: "card-link"%>
              </figcaption>
            </figure>
          </div>
        </div>
      <% end %>
    <% else %>
    <p>No events to show</p>
    <% end %>
  </div>


</div>

app/views/profiles/_my_bookings.html.erb
<div class="container">

<h2 class="clear-header">Joined Games</h2>

  <div class="row">

    <% current_user.bookings.each do |booking| %>
      <div class="col-xs-12 col-sm-6 col-md-4">
        <div class="grid" style="height: 30vmax">
          <figure class="effect-bibi">
            <% background_image = ("sports-photos/" + booking.event.sport.name + ".jpg") %>
            <%= image_tag (background_image) %>
            <figcaption>
            <h2> <%= booking.event.title %> </h2>

              <p><%= (booking.event.description).truncate_words(10) %></p>
              <p><%= booking.event.start_time %> --- <%= booking.booking_state %> </p>
             <%#= link_to 'Chat to Event owner', conversations_path(sender_id: current_user.id, recipient_id: booking.event.user.id), method: "post", class: "btn btn-primary"%>
              <% avatar_url = booking.event.user.photo? ? cl_image_path(booking.event.user.photo.path) : booking.event.user.facebook_picture_url || "https://api.adorable.io/avatars/285/sportl.png" %>
              <%= cl_image_tag (avatar_url), id: "card-avatar" %>
            <%= link_to "", booking_path(booking), class: "card-link"%>
          </figcaption>
        </figure>
      </div>
    </div>
    <% end %>
  </div>
</div>

<%#= link_to booking_path(booking) do %>

<%# end %>

app/views/profiles/_my_requests.html.erb
<div class="container">

  <h2>My requests</h2>

  <div class="row">

  <!-- loop through booking requests -->
    <% current_user.event_bookings.each do |booking| %>
    <!-- set image of person requesting a place -->
      <% if booking.user.photo %>
        <% avatar_url = booking.user.photo.path %>
      <% elsif booking.user.facebook_picture_url %>
        <% avatar_url = booking.user.facebook_picture_url.gsub("square", "large") %>
      <% else %>
        <% avatar_url = "https://api.adorable.io/avatars/285/sportl.png" %>
      <% end %>

      <div class="col-xs-12 col-sm-4 col-md-3">
      <!-- start of profile card -->
        <div class="profile-card">

          <div class="front">
            <div class="background">
              <div class="profile-card-header">
                <div class="profile-card-avatar">
                  <%= cl_image_tag avatar_url, class: "avatar-large text-center" %>
                </div>
              </div>
              <div class="profile-card-body">
                <h3><%= booking.user.first_name %></h3>
                <p>wants to join:</p>
                <div class="match-details">
                  <div class="sport-image">
                    <%= image_tag ("sports/" + booking.event.sport.name + ".png"), style: "width: 7vmin" %>
                    <h6><%= booking.event.title %></h6>
                  </div>
                  <p>on</p>
                  <div class="sport-time">
                    <h6><%= booking.event.start_time.strftime("%e %B %Y") %></h6>
                    <h6><%= booking.event.start_time.strftime("%y:%S") %></h6>
                  </div>
                </div>
              </div>
            </div>
          </div>

          <div class="back">
            <div class="background">
              <div class="profile-card-header">
                <div class="profile-card-avatar">
                  <%= link_to profile_path(booking.user) do %>
                    <%= cl_image_tag avatar_url, class: "avatar-large text-center"%>
                  <% end %>
                </div>
              </div>
              <div class="profile-card-body">
                <h3><% if booking.user.first_name %>
                    <%= booking.user.first_name %>
                  <% else %>
                    user
                    <% end %>
                </h3>
                 <% if booking.user.bio? %>
                  <p><%= booking.user.bio.truncate_words(10) %></p>
                <% else %>
                  <p>no bio</p>
                <% end %>
                <% if booking.pending? %>
                  <div class="match-details">
                    <div class="accept-btn">
                      <%= simple_form_for(booking) do |f| %>
                        <%= f.hidden_field :booking_state, value: 1 %>
                        <%= f.button :submit, "Accept", class: "btn accept-btn" %>
                      <% end %>
                    </div>
                    <div class="deny-btn">
                      <%= simple_form_for(booking) do |f| %>
                        <%= f.hidden_field :booking_state, value: 2 %>
                        <%= f.button :submit, "Deny", class: "btn deny-btn" %>
                      <% end %>
                    </div>
                  </div>
                <% elsif booking.accepted? %>
                  <div class="back-signs">
                    <div class="accepted-sign">
                      <p class="text-center">Accepted</p>
                    </div>
                  </div>
                <% elsif booking.denied? %>
                  <div class="back-signs">
                    <div class="denied-sign">
                      <p class="text-center">Denied</p>
                    </div>
                  </div>
                <% end %>
              </div>
            </div>
          </div> <!-- end of back -->

        </div> <!-- end of profile card -->

      </div> <!-- end of col -->

    <% end %>

  </div> <!-- end of row -->

</div>


<% content_for(:after_js) do %>
   <script>
   $(document).ready(function(){
    $(".profile-card").flip();
   });
   </script>
<% end %>

app/views/profiles/_profile_page.html.erb
<!-- whole page -->
<% if @user.photo? %>
  <% profile_image = @user.photo.path %>
<% elsif  @user.facebook_picture_url %>
  <% profile_image = @user.facebook_picture_url.gsub("square", "large") %>
<% else %>
  <% profile_image = "https://api.adorable.io/avatars/285/sportl.png" %>
<% end %>

<% if @user != current_user %>

<!-- header wrapper for profile page -->
<div class="wrapper">
  <div class="wrapper-contents">
    <%= cl_image_tag profile_image, max_width: 200, crop: :fill, responsive_placeholder: "blank" %>
    <h2 class="text-center"><%= @user.first_name %></h2>
    <h5 class="text-center"><%= @user.created_at.strftime("Joined in %B, %Y") %></h5>
    <%# link_to "Chat to #{@user.first_name}", conversations_path(sender_id: current_user.id, recipient_id: @user.id), method: "post", class: "btn btn-primary"%>
  </div>
</div>
<% end %>
<!-- container for the main content  -->
<div class="container main-content">
  <div class="row">

    <!-- user profile sidebar -->
    <div class="col-sm-3 hidden-xs hidden-sm flexbox-column">
      <div>
        <!-- profile picture -->
        <!-- <div class="square-image"> -->
        <%#= cl_image_tag profile_image, max_width: 200, crop: :fill, responsive_placeholder: "blank" %>
        <!-- </div> -->

        <!-- about me -->
        <div class="panel">
          <div class="panel-header about-me-head text-center">
            <h4>
              About Me
              <span class="black-icon-right"><i class="fa fa-chevron-down"></i></span>
            </h4>
          </div>
          <div class="panel-body about-me-body hide-me">
            <dl>
              <dt style="padding: 4px 0px;"><h5 style="font-weight: bold;" >Favourite Sports</h5></dt>
              <% if @user.sports %>
                <% @user.sports.each do |sport| %>
                <dd><h5><%= image_tag "sports/thumbnails/#{sport.name}.png", width: "30px" %> <%= sport.name %></h5></dd>
              <% end %>
              <% else %>
                <dd>No sports to show </dd>
              <% end %>
            </dl>
          </div>
        </div>

      </div>
    </div>

    <!-- Main Profile -->
    <div class="col-sm-5">

      <!-- small screen only profile pic -->
      <!-- <div class="col-sm-3 hidden-md hidden-lg hidden-xl small-img"> -->
      <%#= cl_image_tag profile_image, crop: :fill, responsive_placeholder: "blank" %>
      <!-- </div> -->

      <div class="info-bit">
        <!-- profile header -->
        <div>
          <h1>Hey, I'm <%= @user.first_name %>!</h1>
          <% if @user.address  %>
            <% location = @user.address %>
          <% else %>
            <% location = "no location to show" %>
          <% end %>
          <h5> <%= location %> · <%= @user.created_at.strftime("Joined in %B, %Y") %></h5>
          <% if @user == current_user %>
            <%= link_to my_profile_edit_path do %>
            Edit profile <i class="fa fa-pencil" aria-hidden="true"></i>
            <% end %>
          <% end %>

        </div>

        <!-- profile main -->
        <div>
          <p> <%= @user.bio %></p>
          <h2>Reviews</h2>
          <h4>Reviews from other players</h4>
          <%#= render "reviews" %>
        </div>

      </div>

    </div>

    <!-- profile page map -->
    <div class="col-sm-4">
      <div class="map">
        <div id="map6" style="width: 100%; height: 600px;"></div>
      </div>
    </div>

  </div>
</div>

<% content_for(:after_js) do %>
        <script>
          $(document).ready(function() {
            $('.about-me-head').click(function() {
              if($('.about-me-head').hasClass('open')){
                $('.about-me-body').slideUp( "slow", function() {});
              }else{
                $('.about-me-body').slideDown( "slow", function() {});
              }
              $('.about-me-head').toggleClass("open");
              $('.black-icon-right > .fa').toggleClass('fa-chevron-up');
              $('.black-icon-right > .fa').toggleClass('fa-chevron-down');
            });
            var handler = Gmaps.build('Google');
            handler.buildMap({ internal: { id: 'map6' } }, function() {
              markers = handler.addMarkers(<%= raw @hash.to_json %>);
              handler.bounds.extendWith(markers);
              handler.fitMapToBounds();
              if (markers.length == 0) {
                handler.getMap().setZoom(2);
              } else if (markers.length == 1) {
                handler.getMap().setZoom(14);
              }
            });
          });
        </script>
        <% end %>

app/views/profiles/created_events.html.erb
<%= render "created_events" %>

app/views/profiles/edit.html.erb
<div class="container">
	<div class="row">
		<div class="col-xs-12 col-md-6 col-md-offset-3">

			<%= link_to my_profile_path do %>
			<h1> <i class="fa fa-undo" aria-hidden="true"></i> </h1>
			<% end %>


			<h1 class="text-center">Edit your profile</h1>

			<div class="edit-form">


				<%= simple_form_for @user, url: my_profile_path do |f| %>

				<%= f.input :username, placeholder: "How users will see you" %>
				<%= f.input :first_name %>
				<%= f.input :last_name %>
       	<%= f.input :gender, label: 'Gender (to help us personalise your searches)', collection: ['Male', 'Female', 'Other']  %>
				<%= f.input :address %>
				<%= f.input :bio %>
				<%= f.input :photo, as: :attachinary %>


				<div class="form-group">

					<label class="control-label check_boxes optional">
						Sports Preferences (to help us personalise your searches)
					</label>

					<input type="hidden" name="user[sport_ids][]" value="">

					<div class="sport-choices">
						<% Sport.all.each do |sport| %>



						<% if @user.sports.include?(sport) %>
							<input class="hidden" type="checkbox" value="<%= sport.id %>" name="user[sport_ids][]" id="user_sport_ids_<%= sport.id %>" checked>
							<label class="sport-choice active" for="user_sport_ids_<%= sport.id %>">
						<% else %>
							<input class="hidden" type="checkbox" value="<%= sport.id %>" name="user[sport_ids][]" id="user_sport_ids_<%= sport.id %>">
							<label class="sport-choice" for="user_sport_ids_<%= sport.id %>">
						<% end %>
								<%= image_tag ("sports/thumbnails/#{sport.name}.png"), style: "width: 7vmin" %> <br>
								<%= sport.name %>
							</label>

						<% end %>
					</div>

				</div>


        <!-- <div class="myFlex">
          <%# Sport.all.each do |sport| %>
          <div class="myFlex2">
            <%# check_box_tag "user[sport_ids][]", sport.id, f.object.sports.include?(sport) %>
            <span><%# sport.name %></span>
          </div>
          <%# end %>
        </div> -->

        <%# f.association :sports, as: :check_boxes %>


        <%#= f.input :sports %>

        <div class="text-center">
          <%= f.submit 'Update your profile', class: "btn btn-primary" %>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/profiles/my_bookings.html.erb
<%= render "my_bookings" %>

app/views/profiles/my_profile.html.erb
<% if @user.photo %>
  <% avatar_url = @user.photo.path %>
<% elsif @user.facebook_picture_url %>
  <% avatar_url = @user.facebook_picture_url.gsub("square", "large") %>
<% else %>
<% avatar_url = "https://api.adorable.io/avatars/285/sportl.png" %>
<% end %>
<!-- header wrapper for profile page -->
<div class="wrapper">
  <div class="wrapper-contents">
    <%= cl_image_tag avatar_url, max_width: 200, crop: :fill, responsive_placeholder: "blank" %>
    <h2 class="text-center"><%= @user.first_name %></h2>
    <h5 class="text-center"><%= @user.created_at.strftime("Joined in %B, %Y") %></h5>
  </div>
</div>

<!-- tabs for each section -->
<div class="profile-dashboard">
  <ul class="nav nav-tabs tabbles">
    <li role="presentation" class="active"><a href="#profile" data-toggle="tab">Profile</a></li>
    <li role="presentation"><a href="#events" data-toggle="tab">Created Events</a></li>
    <li role="presentation"><a href="#bookings" data-toggle="tab">Joined games</a></li>
    <li role="presentation"><a href="#requests" data-toggle="tab">Requests to join</a></li>
  </ul>
</div>

<!-- where each tab goes -->
<div class="tab-content">

<!-- first page is always profile (hence active tab) -->
  <div role="tabpanel" class="tab-pane active" id="profile">
    <%= render "profiles/profile_page" %>
  </div>

<!-- created events page -->
  <div role="tabpanel" class="tab-pane" id="events">
      <%= render "profiles/created_events" %>
  </div>

<!-- joined games page -->
  <div role="tabpanel" class="tab-pane" id="bookings">
    <%= render "profiles/my_bookings" %>
  </div>

<!-- requested games page -->
  <div role="tabpanel" class="tab-pane" id="requests">
    <%= render "profiles/my_requests" %>
  </div>

</div>

app/views/profiles/my_requests.html.erb
<%= render "my_requests"  %>

app/views/profiles/show.html.erb
<%= render "profiles/profile_page" %>