config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users,
  controllers: { omniauth_callbacks: 'users/omniauth_callbacks', :registrations => "users/registrations" }

  root to: 'pages#home'

  get "/my_bookings", to: 'profiles#my_bookings'
  get "/my_requests", to: 'profiles#my_requests'
  get "/created_events", to: 'profiles#created_events'

  get '/my_profile', to: 'profiles#my_profile'
  get "my_profile/edit", to: "profiles#edit"
  patch "my_profile/", to: "profiles#update"
  get "/profile/:id", to: "profiles#show", as: "profile"

  resources :notifications, only: [:index, :destroy]

  # get "/bookings/pending_denied_show/:id", to: "bookings#pending_denied_show", as: "pending"
  get "/bookings/pending/:id", to: "bookings#pending", as: "pending"


  mount Attachinary::Engine => "/attachinary"

  resources :events do
    member do
      get :protected
    end

    resources :bookings, only: [:new, :create]
  end

  resources :chat_rooms, only: [:new, :create, :show, :index]
  mount ActionCable.server => '/cable'



  resources :bookings, except: [:new, :create]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :event
  has_many :notifications, as: :notificationable

  enum booking_state: [:pending, :accepted, :denied]

  def booking_denied
    self.event.missing_player += self.no_players
    self.event.save
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_event, only: [:create]
  before_action :set_booking, only: [:update]


  # list all events
  def index
    @bookings = Booking.all
  end

  # create a new booking
  def new
    @booking = Booking.new
    # authorize @booking
  end

  def pending
    @booking = Booking.find(params[:id])
    authorize @booking

    @events = [@booking.event]
    @hash = Gmaps4rails.build_markers(@events) do |event, marker|
      marker.lat event.latitude
      marker.lng event.longitude
      # marker.infowindow render_to_string(partial: "/flats/map_box", locals: { flat: flat })
    end
  end

  # perform create action
  def create
    @booking = Booking.new(booking_params)
    # authorize @booking
    @booking.event = @event
    @booking.user = current_user

    if @booking.save
      @event.update_players
      Notification.create(content: "#{@booking.user.username} has requested to join '#{@booking.event.title}'", user: @booking.event.user, notificationable: @booking)
      redirect_to pending_path(@booking)
    else
      render :new
    end
  end

  # display particular booking
  def show
    @booking = Booking.find(params[:id])
    authorize @booking
    redirect_to event_path(@booking.event) if current_user == @booking.event.user


    @events = [@booking.event]
    @hash = Gmaps4rails.build_markers(@events) do |event, marker|
      marker.lat event.latitude
      marker.lng event.longitude
      # marker.infowindow render_to_string(partial: "/flats/map_box", locals: { flat: flat })
    end
  end

  # Update booking with accept/deny
  def update
    params[:booking][:booking_state] = params[:booking][:booking_state].to_i
    @booking.update(booking_params)
    if params[:booking][:booking_state] == 2
      #booking is now denied
      @booking.booking_denied
      Notification.create(content: "#{@booking.event.user.username} has denied your request to join '#{@booking.event.title}'", user: @booking.user, notificationable: @booking)
    end
    if params[:booking][:booking_state] == 1
      #create a notif for user and booking
      Notification.create(content: "#{@booking.event.user.username} has accepted your request to join '#{@booking.event.title}'", user: @booking.user, notificationable: @booking)
    end
    redirect_to booking_path(@booking)
  end

  private

  def set_event
    @event = Event.find(params[:event_id])
    authorize @event
  end

  def set_booking
    @booking = Booking.find(params[:id])
    authorize @booking
  end

  def booking_params
    params.require(:booking).permit(:booking_state, :no_players)
  end


end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/views/bookings/_event_booker.html.erb
<!-- details -->

<% if !@booking.event.user.photo %>

  <% profile_image = "https://api.adorable.io/avatars/285/sportl.png" %>
<% elsif @booking.event.user.facebook_picture_url %>
  <% profile_image = @booking.event.user.facebook_picture_url.gsub("square", "large") %>
<% else %>
  <% profile_image = @booking.event.user.photo.path %>
<% end %>

<div class="large-page-container">

  <!-- GAME DETAILS -->
  <div class="row">
    <div class="col-md-6 col-md-offset-3">

      <div style="margin-bottom: 20px; margin-top: 20px">
        <p style="font-size: 25px" class="text-center">
          <%= link_to profile_path(@booking.event.user) do %>
          <%= cl_image_tag profile_image, class: "avatar-large" %>
          <% end %>
          Captain <%= @booking.event.user.username %> <%= "will see you there" if @booking.booking_state == "accepted" %>
        </p>
        <p class="text-center">
          <% if @booking.event.start_time.today? %>
            Today, <%= @booking.event.start_time.strftime("%H:%M") %>
          <% elsif @booking.event.start_time.to_date == Date.tomorrow %>
            Tomorrow, <%= @booking.event.start_time.strftime("%H:%M") %>
          <% else %>
            <%= @booking.event.start_time.strftime("%a %d %b, %H:%M") %>
          <% end %>
        </p>
        <div class="text-center">
          <%= link_to "Chat to #{@booking.event.user.username}", chat_rooms_path(sender_id: current_user.id, recipient_id: @booking.event.user.id), method: "post", class: "btn btn-primary" %>
        </div>
      </div>

    </div>
  </div>

  <div class="grey-container">
    <h3 class="text-center">GAME DETAILS</h3>
    <div class="row"> <!-- beginning of main content -->
      <div class="col-md-8"> <!-- left side of main -->

        <div class="row"> <!-- event details top -->
          <div class="col-sm-6">

            <!-- MATCH DETAILS -->
            <div class="flex-container-column white-box">

              <h5 class="text-center">LEVEL</h5>
              <p class="text-center">
                <% @booking.event.level.times do %>
                  <i class="fa fa-square colour-icon" aria-hidden="true"></i>
                <% end %>
                <% (3 - @booking.event.level).times do %>
                  <i class="fa fa-square-o colour-icon" aria-hidden="true"></i>
                <% end %>
              </p>
              <h5 class="text-center">PLAYERS NEEDED</h5>
              <p class="text-center">
                <% @booking.event.missing_player.times do %>
                  <i class="fa fa-user colour-icon" aria-hidden="true"></i>
                <% end %>
              </p>
              <h5 class="text-center">GENDERED? </h5>
              <p class="text-center">
                <% if @booking.event.gender.downcase == "female" %>
                  <i class="fa fa-venus colour-icon"></i> ladies
                <% elsif @booking.event.gender.downcase == "male" %>
                  <i class="fa fa-mars colour-icon"></i> mens
                <% else %>
                  mixed
                <% end %>
              </p>

            </div> <!-- end of flex-container-column -->
          </div><!-- end of col-sm-6 -->

          <div class="col-sm-6">

            <!-- EXTRA INFO -->
            <div class="flex-container-column white-box">
              <h5 class="text-center">DETAILS</h5>
              <div class="flex-space-between">
                <p><i class="fa fa-calendar"></i></p>
                <p>
                  <% if @booking.event.start_time.to_date == @booking.event.end_time.to_date %>
                    <%= @booking.event.start_time.strftime("%A %d %B") %>
                  <% else %>
                    <%= @booking.event.start_time.strftime("%A %d %B") %> - <%= @booking.event.end_time.strftime("%A %d %B") %>
                  <% end %>
                </p>
              </div>
               <div class="flex-space-between">
                <p><i class="fa fa-clock-o"></i></p>
                <p>
                  <% if @booking.event.start_time.to_date == @booking.event.end_time.to_date %>
                    <%= @booking.event.start_time.strftime("%H:%M") %> - <%= @booking.event.end_time.strftime("%H:%M") %>
                  <% else %>
                    <%= @booking.event.start_time.strftime("%H:%M") %> <span class="grey-text">(<%= @booking.event.start_time.strftime("%A %d") %>)</span> - <%= @booking.event.end_time.strftime("%H:%M") %> <span class="grey-text">(<%= @booking.event.end_time.strftime("%A %d") %>)</span>
                  <% end %>
                </p>
              </div>
              <div class="flex-space-between">
                <p><i class="fa fa-suitcase"></i></p>
                <p>
                  <% if @booking.event.requirements == "" %>
                      None
                  <% else %>
                    <%= @booking.event.requirements %>
                  <% end %>
                </p>
              </div>

            </div> <!-- end of flex-container-column -->
          </div> <!-- end of col-sm-6 -->

        </div> <!-- end of row -->

        <div class="row">
          <div class="col-sm-12">

            <div class="flex-container-column white-box">
              <h5 class="text-center">DESCRIPTION</h5>
              <p><%= @booking.event.description %></p>
            </div>

          </div>
        </div> <!-- end of row -->

        <div class="row"> <!-- final row (captain and players) -->

          <!-- CAPTAIN DETAILS -->
          <div class="col-sm-9">
            <div class="flex-container-column white-box">
              <h5 class="text-center">CAPTAIN</h5>
              <div class="text-center">
                <%= image_tag profile_image, class: "avatar-xl" %>
              </div>
              <h6 class="text-center" style="padding: 0px; margin: 5px;"><%= @booking.event.user.first_name %> ( <%= @booking.event.user.username %>)</h6>
              <h6 class="text-center" style="padding: 0px; margin: 5px;"><%= @booking.event.user.created_at.strftime("Joined in %B, %Y") %></h6>
              <p style="margin-top: 10px;"><%= @booking.event.user.bio %></p>
            </div>
          </div> <!-- end of captain details col-sm-9 -->

          <!-- PLAYER DETAILS -->
          <div class="col-sm-3">
            <div class="flex-container-column white-box">
              <h5 class="text-center">OTHER PLAYERS</h5>
              <% if @booking.event.players.length > 0 %>
              <div class="row">
                <% @booking.event.players.each do |player| %>
                  <div class="col-xs-6">
                    <% if player.user.photo? %>
                      <% profile_image = player.user.photo.path %>
                    <% elsif player.user.facebook_picture_url %>
                      <% profile_image = player.user.facebook_picture_url.gsub("square", "large") %>
                    <% else %>
                      <% profile_image = "https://api.adorable.io/avatars/285/sportl.png" %>
                    <% end %>
                    <%= link_to profile_path(player.user), style: "text-decoration: none;" do %>
                      <div class="text-center">
                        <div class="badge-container">
                          <%= cl_image_tag profile_image, max_width: 200, crop: :fill, responsive_placeholder: "blank", class: "avatar-large" %>
                          <% if current_user.friend_uids.include? player.user.uid %>
                            <div class="badge badge-blue" style="position: absolute; top: 5px;">f</div>
                          <% end %>
                        </div>
                      </div>
                      <div class="text-center">
                      <%= player.user.username %>
                      </div>
                    <% end %>
                  </div>
                <% end %>
              </div>
              <% end %>
            </div>
          </div> <!-- end of player details col-sm-3 -->

        </div> <!-- end of final row (captain and players) -->
      </div> <!-- end of left main col-md-8 -->

      <!-- MAP -->
      <div class="col-md-4">
        <div class="flex-container-column white-box">
          <h5 class="text-center">LOCATION</h5>
          <p><strong><%= @booking.event.venue_name %></strong></p>
          <p><%= @booking.event.full_address %></p>
          <div id="map1" style="width: 100%; height: 500px;"></div>
        </div>
      </div>

    </div>  <!-- end of row -->
  </div> <!-- end of grey-container -->

</div> <!-- end of page/container -->

 <script>
  <% content_for(:after_js) do %>
    <%= javascript_tag do %>
      $(document).on('ready', function() {
        var handler = Gmaps.build('Google');
        handler.buildMap({ internal: { id: 'map1' } }, function(){

         <% @hash = Gmaps4rails.build_markers(@booking.event) do |event, marker| %>
           markers = handler.addMarkers([
               {
                 lat: <%= event.latitude %>,
                 lng: <%= event.longitude %>,
                 picture: {
                   url: "<%= image_path ("sports/thumbnails/" + event.sport.name + ".png") %>",
                   width:  50,
                   height: 50
                 }
               }
             ]);
           <% end %>

         markers.forEach(function(marker) {
           handler.bounds.extendWith(marker);
         });
         handler.fitMapToBounds();
        handler.getMap().setZoom(14);
       });
      });
    <% end %>
  <% end %>
</script>

app/views/bookings/_form.html.erb
<%= simple_form_for [@event, @booking], html: {class: 'form-inline'} do |f| %>
    <%= f.input :no_players, label: 'Number of players', collection: 1..(@event.missing_player), default: 1, method: :update%>
    <% if user_signed_in? %>
      <%= f.button :submit, class: "btn btn-primary btn-lg", value: "Request to join!" %>
    <% else %>
      <%= link_to "Request to join!", protected_event_path(@event), class: 'btn btn-primary btn-lg' %>
    <% end %>

<% end %>

<style>
  #booking_no_players {
    margin: 0px 10px;
  }
</style>

app/views/bookings/pending.html.erb
<% if @booking.event.user.photo %>
  <% avatar_url = cl_image_path(@booking.event.user.photo.path) %>
<% elsif @booking.event.user.facebook_picture_url %>
  <% avatar_url = @booking.event.user.facebook_picture_url %>
<% else %>
  <% avatar_url = "https://api.adorable.io/avatars/285/sportl.png" %>
<% end %>


<div class="full-container">
  <%= image_tag ('logo.png'), class: "pending-denied-logo" %>
  <div class="full-container-content text-center">
    <%= image_tag ("sports/" + @booking.event.sport.name + ".png"), style: "width: 60px" %>

    <h1>Thanks, <%= @booking.user.first_name %>!</h1>
    <p>
      You want to join <strong>"<%= @booking.event.title %>"</strong>.
    </p>
    <p>
      Captain <%= @booking.event.user.first_name %> will get back to you
    </p>
    <p>
    <%= image_tag avatar_url, class: "avatar-large" %>
    <%= link_to "Ask captain a question", chat_rooms_path(sender_id: current_user.id, recipient_id: @booking.event.user.id), method: :post %></p>
  </div>
</div>



<% if false %>

<div class="show-banner" style="background-image: linear-gradient(-225deg, rgba(0, 0, 0, 0.4) 0%, rgba(0, 0, 0, 0.4) 50%), url(<%= image_path "sports-photos/#{@booking.event.sport.name}.jpg" %>); width: 100%; background-size: cover; height: 50vh; background-position: center;">
 <div class="container text-center">
   <h1 style="padding-top: 10vh; font-size: 50px">
     <span class="banner-event-title"> <%= @booking.event.title %> | </span>
     <span class="banner-sport-name"> <%= @booking.event.sport.name %> </span>
   </h1>
 </div>
</div>

<div class="booking-pending-wrapper">
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-md-7">
        <p style="font-size: 23px;">
          <%= link_to profile_path(@booking.event.user) do %>
          <% avatar_url = @booking.event.user.facebook_picture_url.present? ? @booking.event.user.facebook_picture_url : "https://api.adorable.io/avatars/285/sportl.png" || @booking.event.user.photo.path %>
          <%= cl_image_tag avatar_url, class: "avatar-large" %>
          <% end %>
          Captain <%= @booking.event.user.username %> <%= "will see you there" if @booking.booking_state == "accepted" %>
        </p>

        <p style="font-size: 23px;">
          <% if @booking.event.start_time.today? %>
          Today, <%= @booking.event.start_time.strftime("%H:%M") %>
          <% elsif @booking.event.start_time.to_date == Date.tomorrow %>
          Tomorrow, <%= @booking.event.start_time.strftime("%H:%M") %>
          <% else %>
          <%= @booking.event.start_time.strftime("%a %d %b, %H:%M") %>
          <% end %>
        </p>

        <div style="float:right;">
          <%= link_to "chat to event owner", chat_rooms_path(sender_id: current_user.id, recipient_id: @booking.event.user.id), method: :post, class: "btn btn-success btn-lg" %>
          <%# link_to "Chat to #{@booking.event.user.username}", conversations_path(sender_id: current_user.id, recipient_id: @booking.event.user.id), method: "post", class: "btn btn-primary btn-lg"  %>
        </div>
      </div>
      <div class="col-xs-12 col-md-5">
        <h3 style="margin-top: 0px;" >
          status:
          <% if @booking.booking_state == "pending" %>
          <span style="color: orange;">pending</span>
          <% elsif @booking.booking_state == "denied" %>
          <span style="color: red;">denied</span>
          <% else %>
          <span style="color: green;">accepted</span>
          <% end %>
        </h3>
      </div>
    </div>
  </div>
</div>


<% end %>

app/views/bookings/pending_denied_show.html.erb
<% if @booking.event.user.photo %>
  <% avatar_url = cl_image_path(@booking.event.user.photo.path) %>
<% elsif @booking.event.user.facebook_picture_url %>
  <% avatar_url = @booking.event.user.facebook_picture_url %>
<% else %>
  <% avatar_url = "https://api.adorable.io/avatars/285/sportl.png" %>
<% end %>


<div class="full-container">
  <%= image_tag ('logo.png'), class: "pending-denied-logo" %>
  <div class="full-container-content text-center">
    <%= image_tag ("sports/" + @booking.event.sport.name + ".png"), style: "width: 60px" %>

    <h1>Thanks, <%= @booking.user.first_name %>!</h1>
    <p>
      You want to join <strong>"<%= @booking.event.title %>"</strong>.
    </p>
    <p>
      Captain <%= @booking.event.user.first_name %> will get back to you
    </p>
    <p>
    <%= image_tag avatar_url, class: "avatar-large" %>
    <%= link_to "Ask captain a question", chat_rooms_path(sender_id: current_user.id, recipient_id: @booking.event.user.id), method: :post %></p>
  </div>
</div>



<% if false %>

<div class="show-banner" style="background-image: linear-gradient(-225deg, rgba(0, 0, 0, 0.4) 0%, rgba(0, 0, 0, 0.4) 50%), url(<%= image_path "sports-photos/#{@booking.event.sport.name}.jpg" %>); width: 100%; background-size: cover; height: 50vh; background-position: center;">
 <div class="container text-center">
   <h1 style="padding-top: 10vh; font-size: 50px">
     <span class="banner-event-title"> <%= @booking.event.title %> | </span>
     <span class="banner-sport-name"> <%= @booking.event.sport.name %> </span>
   </h1>
 </div>
</div>

<div class="booking-pending-wrapper">
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-md-7">
        <p style="font-size: 23px;">
          <%= link_to profile_path(@booking.event.user) do %>
          <% avatar_url = @booking.event.user.facebook_picture_url.present? ? @booking.event.user.facebook_picture_url : "https://api.adorable.io/avatars/285/sportl.png" || @booking.event.user.photo.path %>
          <%= cl_image_tag avatar_url, class: "avatar-large" %>
          <% end %>
          Captain <%= @booking.event.user.username %> <%= "will see you there" if @booking.booking_state == "accepted" %>
        </p>

        <p style="font-size: 23px;">
          <% if @booking.event.start_time.today? %>
          Today, <%= @booking.event.start_time.strftime("%H:%M") %>
          <% elsif @booking.event.start_time.to_date == Date.tomorrow %>
          Tomorrow, <%= @booking.event.start_time.strftime("%H:%M") %>
          <% else %>
          <%= @booking.event.start_time.strftime("%a %d %b, %H:%M") %>
          <% end %>
        </p>

        <div style="float:right;">
          <%= link_to "chat to event owner", chat_rooms_path(sender_id: current_user.id, recipient_id: @booking.event.user.id), method: :post, class: "btn btn-success btn-lg" %>
          <%# link_to "Chat to #{@booking.event.user.username}", conversations_path(sender_id: current_user.id, recipient_id: @booking.event.user.id), method: "post", class: "btn btn-primary btn-lg"  %>
        </div>
      </div>
      <div class="col-xs-12 col-md-5">
        <h3 style="margin-top: 0px;" >
          status:
          <% if @booking.booking_state == "pending" %>
          <span style="color: orange;">pending</span>
          <% elsif @booking.booking_state == "denied" %>
          <span style="color: red;">denide</span>
          <% else %>
          <span style="color: green;">accepted</span>
          <% end %>
        </h3>
      </div>
    </div>
  </div>
</div>


<% end %>

app/views/bookings/show.html.erb
<div class="show-banner" style="background-image: linear-gradient(-225deg, rgba(0, 0, 0, 0.4) 0%, rgba(0, 0, 0, 0.4) 50%), url(<%= image_path "sports-photos/#{@booking.event.sport.name}.jpg" %>); width: 100%; background-size: cover; height: 50vh; background-position: center;">
 <div class="container text-center">
   <h1 style="padding-top: 10vh; font-size: 50px">
     <span class="banner-event-title"> <%= @booking.event.title %> | </span>
     <span class="banner-sport-name"> <%= @booking.event.sport.name %> </span>
   </h1>
 </div>
</div>


  <%= render 'event_booker' %>

app/views/bookings/spare_booker.html.erb
<div class="booking-wrapper">
  <div class="container">
    <div class="row booking-event-wrapper">
        <div class="col-xs-12 col-md-6">
          <p style="font-size: 25px;">
            <%= link_to profile_path(@booking.event.user) do %>
            <% avatar_url = @booking.event.user.facebook_picture_url.present? ? @booking.event.user.facebook_picture_url : @booking.event.user.photo.path || "https://api.adorable.io/avatars/285/sportl.png" %>
            <%= cl_image_tag avatar_url, class: "avatar-large" %>
            <% end %>
            Captain <%= @booking.event.user.username %> <%= "will see you there" if @booking.booking_state == "accepted" %>
          </p>

          <p>
            <% if @booking.event.start_time.today? %>
              Today, <%= @booking.event.start_time.strftime("%H:%M") %>
            <% elsif @booking.event.start_time.to_date == Date.tomorrow %>
              Tomorrow, <%= @booking.event.start_time.strftime("%H:%M") %>
            <% else %>
              <%= @booking.event.start_time.strftime("%a %d %b, %H:%M") %>
            <% end %>
          </p>

          <%= link_to "Chat to #{@booking.event.user.username}", chat_rooms_path(sender_id: current_user.id, recipient_id: @booking.event.user.id), method: "post", class: "btn btn-primary" %>
        </div>
      <div class="col-xs-12 col-md-6">
        <h3>See you at:<%= @booking.event.venue_name %>, <%= @booking.event.full_address %></h3>
        <div id="map2" style="width: 525px; height: 40vh; border-radius: 5px;"></div>
      </div>
    </div>
  </div>
</div>

<% content_for(:after_js) do %>
<script>
  $(document).on('ready', function() {
    var handler = Gmaps.build('Google');
    handler.buildMap({ internal: { id: 'map2' } }, function(){

      <% @hash = Gmaps4rails.build_markers(@booking.event) do |event, marker| %>
      markers = handler.addMarkers([
      {
       lat: <%= event.latitude %>,
       lng: <%= event.longitude %>
     }
     ]);
      <% end %>

      markers.forEach(function(marker) {
       handler.bounds.extendWith(marker);
     });
      handler.fitMapToBounds();
      handler.getMap().setZoom(14);
    });
  });
</script>
<% end %>