config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users,
  controllers: { omniauth_callbacks: 'users/omniauth_callbacks', :registrations => "users/registrations" }

  root to: 'pages#home'

  get "/my_bookings", to: 'profiles#my_bookings'
  get "/my_requests", to: 'profiles#my_requests'
  get "/created_events", to: 'profiles#created_events'

  get '/my_profile', to: 'profiles#my_profile'
  get "my_profile/edit", to: "profiles#edit"
  patch "my_profile/", to: "profiles#update"
  get "/profile/:id", to: "profiles#show", as: "profile"

  resources :notifications, only: [:index, :destroy]

  # get "/bookings/pending_denied_show/:id", to: "bookings#pending_denied_show", as: "pending"
  get "/bookings/pending/:id", to: "bookings#pending", as: "pending"


  mount Attachinary::Engine => "/attachinary"

  resources :events do
    member do
      get :protected
    end

    resources :bookings, only: [:new, :create]
  end

  resources :chat_rooms, only: [:new, :create, :show, :index]
  mount ActionCable.server => '/cable'



  resources :bookings, except: [:new, :create]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_card.html.erb
<div class="card">
  <div class="sport-image">
    <%= image_tag ("sports-photos/" + booking.event.sport.name + ".jpg"), style: "width: 15vmin" %>
  </div>
  <div class="card-info">
    <h3><%= booking.event.title %></h3>
    <p><%= booking.event.start_time %></p>
    <br>
    <h3><%= booking.booking_state %></h3>
  </div>
  <div class="right-side">
    <% avatar_url = booking.event.user.photo? ? cl_image_path(booking.event.user.photo.path) : booking.event.user.facebook_picture_url || "https://api.adorable.io/avatars/285/sportl.png" %>
    <%= image_tag avatar_url, class: "avatar" %>
  </div>
  <%= link_to "", booking_path(booking), class:"card-link" %>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice.html_safe %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert.html_safe %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-items">
    <div class="footer-icon">
      <%= link_to "#" do %>
      <i class="fa fa-facebook" aria-hidden="true"></i>
      <% end %>
    </div>
      <div class="footer-icon">
      <%= link_to "#" do %>
      <i class="fa fa-instagram" aria-hidden="true"></i>
      <% end %>
    </div>
        <div class="footer-icon">
    <%= link_to "#" do %>
      <i class="fa fa-twitter" aria-hidden="true"></i>
      <% end %>
    </div>

    </div>

  <div class="footer-items">
    <div class="item">
      <%= link_to "about us", "#", class: "footer_link" %>
    </div>
    <div class="item">
      help
    </div>
    <div class="item">
      contact us
    </div>
  </div>
</div>

app/views/shared/_home_nav.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <% if user_signed_in? %>
    <div class="navbar-wagon-right">
      <div>
        <%= link_to root_path, class: "navbar-wagon-brand" do %>
          <%= image_tag "logo_writing.png" %>
        <% end %>
      </div>
      <div class="navbar-wagon-item" style="margin-left: 20px">
        <%= link_to "find a player", new_event_path %>
      </div>
    </div>
  <% else %>
    <div>
      <%= link_to root_path, class: "navbar-wagon-brand" do %>
        <%= image_tag "logo.png" %>
      <% end %>
      <%= link_to "Sportl.", root_path, id: "logo-name"%>
    </div>
  <% end %>
  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <!-- Search form -->
    <!-- <form action="" class="navbar-wagon-search">
      <input type="text" class="navbar-wagon-search-input" placeholder="Search something">
      <button type="submit" class="navbar-wagon-search-btn">
        <i class="fa fa-search"></i>
      </button>
    </form> -->

    <!-- Different navigation if login or not -->
    <% if user_signed_in? %>

      <!-- my events link -->
      <div class="navbar-wagon-item navbar-wagon-link">
        <div class="dropdown">
          <%= link_to "my events", '#', class: "dropdown-toggle", id: "dropdownMenu2", "data-toggle" => "dropdown" %>

          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li><%= link_to "Joined events", my_bookings_path %></li>
            <li><%= link_to "Created events",  created_events_path %></li>
            <li><%= link_to "Requests", my_requests_path %></li>
          </ul>
        </div>
      </div>

      <!-- Notification -->
      <div class="navbar-wagon-item navbar-wagon-link">
        <%= link_to "my messages", conversations_path %>
      </div>


      <%# link_to "#", class: "navbar-wagon-item navbar-wagon-link" do %>
        <!-- <div class="badge-container"> -->
<!--           <i class="fa fa-envelope-o"></i>
          <div class="badge badge-blue">3</div> -->
        <!-- </div> -->
      <%# end %>

      <!-- Profile picture and dropdown -->
      <div class="navbar-wagon-item navbar-wagon-link">
        <div class="dropdown">


          <%= link_to current_user.username, "#", class: "dropdown-toggle", id: "username-link", "data-toggle" => "dropdown" %>
          <% if !current_user.photo %>
            <% avatar_url = "https://api.adorable.io/avatars/285/sportl.png" %>
          <% else %>
            <% avatar_url = current_user.photo.path || current_user.facebook_picture_url %>
          <% end %>
          <%= cl_image_tag avatar_url, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>


          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to my_profile_path do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to root_path do %>
                <i class="fa fa-home"></i>  <%= t(".profile", default: "Home") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>

    <% else %>

    <!-- Button (call-to-action) -->
    <%# link_to t(".top_call_to_action", default: "Post stuff"), "#", class: "navbar-wagon-item navbar-wagon-button btn" %>
      <!-- Login text link -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>

  </div>


  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="sportl-navbar" id="hover-nav">

  <!-- Logo -->
  <div class="navbar-sportl-sides">
    <div>
      <%= link_to root_path, class: "navbar-sportl-brand hidden-xs" do %>
        <%= image_tag "logo_writing.png" %>
      <% end %>
    </div>
    <div>
      <%= link_to root_path, class: "small-sportl-brand visible-xs" do %>
      <%= image_tag "logo_writing.png" %>
    </div>
  </div>
  <% end %>
  <!-- end logo -->

  <!-- left side of navbar -->
  <div class="left-side-navbar">
    <div class="navbar-sportl-sides hidden-xs hidden-sm">
      <div class="navbar-sportl-item navbar-sportl-link">
        <% if user_signed_in? %>
          <div class="navbar-sportl-item" style="margin-left: 20px">
          <!-- SEARCH -->
            <%= link_to events_path do %>
            search
              <!-- <i class="fa fa-search" style="font-size: 40px"></i> -->
            <% end %>
          </div>
        <% end %>
      </div>
      <div class="navbar-sportl-item navbar-sportl-link">
        <% if user_signed_in? %>
          <div class="navbar-sportl-item" style="margin-left: 20px">
          <!-- NEW EVENT -->
            <%= link_to new_event_path do %>
              create event
              <!-- <i class="fa fa-plus" style="font-size: 40px"></i> -->
            <% end %>
          </div>
        <% end %>
      </div>
      <!-- <div class="navbar-sportl-item navbar-sportl-link"> -->
        <%# if user_signed_in? %>
        <!-- CAPTAIN MENU -->
          <!-- <div class="navbar-sportl-item" style="margin-left: 20px"> -->
            <%#= link_to "captain", "#", class: "hvr-grow toggle-captain" %>
          <!-- </div> -->
        <%# end %>
      <!-- </div> -->
    </div>
  </div>
  <!-- end of left side -->

  <!-- right side of navbar -->
  <div class="right-side-navbar">
    <div class="navbar-sportl-sides hidden-xs hidden-sm">
      <!-- <div class="navbar-sportl-item navbar-sportl-link">
        <%# if user_signed_in? %>
          <div class="navbar-sportl-item">
          PLAYER MENU
            <%#= link_to "player", "#", class: "hvr-grow toggle-player" %>
          </div>
        <%# end %>
      </div> -->
      <!-- PROFILE -->
      <div class="navbar-sportl-item navbar-sportl-link">
        <% if user_signed_in? %>
          <div class="navbar-sportl-item" style="margin-left: 20px">
            <%= link_to "#", class: "hvr-grow toggle-profile" do%>
                my profile
            <% end %>
          </div>
        <% end %>
      </div>
      <div class="navbar-sportl-item navbar-sportl-link">
        <% if user_signed_in? %>
        <!-- MESSAGES -->
          <div class="navbar-sportl-item" style="margin-left: 20px">

            <%= link_to "#", class: "hvr-grow toggle-messages" do %>
              <!-- <i class="fa fa-envelope-o" style="font-size: 40px"></i> -->
              <% if user_signed_in? && (unread_messages + current_user.notifications.count != 0) %>
               messages  (<%= unread_messages + current_user.notifications.count %>)
               <% else %>
               messages
               <% end %>

            <% end %>
          </div>
        <% end %>
      </div>
    </div>
  </div>

  <div>
    <% if !user_signed_in? %>
      <div class="sign-in-btn">
        <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-sportl-item-item navbar-sportl-item-link hvr-grow" %>
      </div>
    <% end %>
  </div>


  <!-- Dropdown list appearing on mobile only -->
  <% if user_signed_in? %>
    <div class="navbar-sportl-item hidden-md hidden-lg" style="position: absolute; right: 10px;">
      <div class="dropdown">
        <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
        <ul class="dropdown-menu dropdown-menu-sides navbar-sportl-dropdown-menu dropdown-menu-right">
            <li><%= link_to "my profile", my_profile_path %></li>
            <li><%= link_to "messages", chat_rooms_path %></li>
            <li><%= link_to "notifications", notifications_path %></li>
            <li><%= link_to "log out", destroy_user_session_path, method: :delete %></li>
        </ul>
      </div>
    </div>
  <% end %>

</div>

<!-- FIND EVENT DROPDOWN -->
<div class="sub-nav-holder nav-find">
  <div class="sub-nav-inner">
    <div class="sub-nav-link">
      <%= form_tag("events", method: "get", class: "form-inline", id: "nav-sport-form") do %>
        <div class="form-group">
          <%= select_tag "sports", options_for_select(sports_list) %>
        </div>
        <div class="form-group date-picker">
          <div class='input-group date' id='datetimepicker5' >
            <input type='text' class="form-control" name="start" placeholder="from" style="width: 120px" />
            <span class="input-group-addon">
            <span class="fa fa-calendar"></span>
            </span>
          </div>
        </div>
        <div class="form-group date-picker">
          <div class='input-group date' id='datetimepicker6' >
            <input type='text' class="form-control" name="end" placeholder="until" style="width: 120px" />
            <span class="input-group-addon">
            <span class="fa fa-calendar"></span>
            </span>
          </div>
        </div>
        <div class="form-group">
          <%= select_tag "missing_player", options_for_select(party_size), placeholder: "Party size" %>
        </div>
        <div class="form-group">
         <%= select_tag "gender", options_for_select(['Any', 'Male', 'Female']), placeholder: "Any" %>
       </div>
        <div class="form-group">
          <input type="text" name="location" placeholder="Postcode" class="form-control">
        </div>
        <div class="form-group">
          <input id="radius" name="radius" type="number" placeholder="Radius (km)" class="form-control" id="radius" />
        </div>
        <%= submit_tag("Search", class: "btn btn-primary sport-form-submit") %>
        <div id="slider"></div>
    <% end %>
    </div>
  </div>
</div>


<!-- CAPTAIN DROPDOWN -->
<!-- <div class="sub-nav-holder nav-captain">
  <div class="sub-nav-inner">
    <div class="sub-nav-link">
      <%#= link_to "created events", created_events_path %>
    </div>
    <div class="sub-nav-link">
      <%#= link_to "player requests", my_requests_path %>
    </div>
  </div>
</div> -->

<!-- PLAYER DROPDOWN -->
<!-- <div class="sub-nav-holder nav-player">
  <div class="sub-nav-inner">
    <div class="sub-nav-link">
      <%#= link_to "joined events", my_bookings_path %>
    </div>
  </div>
</div> -->

<!-- PROFILE DROPDOWN -->
<div class="sub-nav-holder nav-profile">
  <div class="sub-nav-inner-profile">
    <!-- CAPTAIN -->
    <div class="captain-stuff flex-container-column">
      <div class="text-center inner-profile-title"> Captain menu </div>
      <div class="myFlex">
        <div class="sub-nav-link nav-inner-link">
          <%= link_to "player requests", my_requests_path %>
        </div>
        <div class="sub-nav-link nav-inner-link">
          <%= link_to "created events", created_events_path %>
        </div>
      </div>
    </div>
    <!-- PLAYER -->
    <div class="player-stuff flex-container-column">
      <div class="text-center inner-profile-title"> Player menu </div>
      <div class="myFlex">
        <div class="sub-nav-link nav-inner-link">
          <%= link_to "joined events", my_bookings_path %>
        </div>
      </div>
    </div>
    <!-- PROFILE -->
    <div class="profile-stuff flex-container-column">
      <div class="text-center inner-profile-title"> Profile </div>
        <div class="myFlex">
          <div class="sub-nav-link nav-inner-link">
            <%= link_to my_profile_path do %>
              my page
            <% end %>
          </div>
          <div class="sub-nav-link nav-inner-link">
            <%= link_to destroy_user_session_path, method: :delete do %>
              <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "log out") %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<!-- MESSAGES DROPDOWN -->
<div class="sub-nav-holder nav-messages">
  <div class="sub-nav-inner">
    <div class="sub-nav-link">
    <% if user_signed_in? && unread_messages != 0 %>
      <%= link_to "chats (#{unread_messages})", chat_rooms_path %>
      <% else %>
      <%= link_to "chats", chat_rooms_path %>
      <% end %>
    </div>
    <div class="sub-nav-link">
      <% if user_signed_in? && current_user.notifications.count != 0 %>
        <%= link_to "notifications (#{current_user.notifications.count})", notifications_path %>
      <% else %>
        <%= link_to "notifications", notifications_path %>
      <% end %>
    </div>
  </div>
</div>

<!-- JAVASCRIPT -->

<% content_for(:after_js) do %>
  <%= javascript_tag do %>
    $(document).ready(function() {
      $('.toggle-find').click(function() {
        $('.nav-player').slideUp("medium");
        $('.nav-profile').slideUp("medium");
        $('.nav-player').slideUp("medium");
        $('.nav-messages').slideUp("medium");
        $('.nav-find').slideToggle("slow");
        $('.nav-find').css({display: 'flex'});
      })
      $('.toggle-captain').click(function() {
        $('.nav-find').slideUp("medium");
        $('.nav-player').slideUp("medium");
        $('.nav-profile').slideUp("medium");
        $('.nav-messages').slideUp("medium");
        $('.nav-captain').slideToggle("slow");
        $('.nav-captain').css({display: 'flex'});
      });
      $('.toggle-player').click(function() {
        $('.nav-find').slideUp("medium");
        $('.nav-captain').slideUp("medium");
        $('.nav-profile').slideUp("medium");
        $('.nav-messages').slideUp("medium");
        $('.nav-player').slideToggle("slow");
        $('.nav-player').css({display: 'flex'});
      });
      $('.toggle-profile').click(function() {
        $('.nav-find').slideUp("medium");
        $('.nav-captain').slideUp("medium");
        $('.nav-player').slideUp("medium");
        $('.nav-messages').slideUp("medium");
        $('.nav-profile').slideToggle("slow");
        $('.nav-profile').css({display: 'flex'});
      });
      $('.toggle-messages').click(function() {
        $('.nav-find').slideUp("medium");
        $('.nav-captain').slideUp("medium");
        $('.nav-player').slideUp("medium");
        $('.nav-profile').slideUp("medium");
        $('.nav-messages').slideToggle("slow");
        $('.nav-messages').css({display: 'flex'});
      });
      $('#datetimepicker5').datetimepicker({
          format: "DD/MM/YYYY HH:mm",
          sideBySide: true,
          minDate: moment(),
          stepping: 5,
          icons: {
            previous: 'glyphicon glyphicon-chevron-left',
            next: 'glyphicon glyphicon-chevron-right'
          }
        });

        $('#datetimepicker6').datetimepicker({
          format: "DD/MM/YYYY HH:mm",
          sideBySide: true,
          minDate: moment(),
          stepping: 5,
        });
        $("#datetimepicker5").on("dp.change", function (e) {
            $('#datetimepicker6').data("DateTimePicker").minDate(e.date);
            $('#datetimepicker6').data("DateTimePicker").defaultDate(e.date);
        });
    });
  <% end %>

<% end %>