config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users,
  controllers: { omniauth_callbacks: 'users/omniauth_callbacks', :registrations => "users/registrations" }

  root to: 'pages#home'

  get "/my_bookings", to: 'profiles#my_bookings'
  get "/my_requests", to: 'profiles#my_requests'
  get "/created_events", to: 'profiles#created_events'

  get '/my_profile', to: 'profiles#my_profile'
  get "my_profile/edit", to: "profiles#edit"
  patch "my_profile/", to: "profiles#update"
  get "/profile/:id", to: "profiles#show", as: "profile"

  resources :notifications, only: [:index, :destroy]

  # get "/bookings/pending_denied_show/:id", to: "bookings#pending_denied_show", as: "pending"
  get "/bookings/pending/:id", to: "bookings#pending", as: "pending"


  mount Attachinary::Engine => "/attachinary"

  resources :events do
    member do
      get :protected
    end

    resources :bookings, only: [:new, :create]
  end

  resources :chat_rooms, only: [:new, :create, :show, :index]
  mount ActionCable.server => '/cable'



  resources :bookings, except: [:new, :create]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/event.rb
class Event < ApplicationRecord
  LEVELS = %w(casual competitive serious)

  belongs_to :user
  belongs_to :sport
  has_many :bookings
  has_many :players
  accepts_nested_attributes_for :players

  validates :missing_player, :sport, :title, :postcode, :start_time, :end_time, :level, presence: true
  validates :level, inclusion: { in: [1,2,3], allow_nil: false }

  has_many :notifications, as: :notificationable
  validates :gender, presence: true

  geocoded_by :full_address
  # reverse_geocoded_by :latitude, :longitude do |obj, results|
  #   if geo = results.first
  #     obj.g_city = geo.city
  #     obj.g_postcode = geo.postal_code
  #     obj.g_country = geo.country_code
  #     obj.g_address = geo.address
  #   end
  # end

  after_validation :geocode, if: :postcode_changed?

  def full_address
    [address, city, postcode, country].compact.join(', ')
  end

  # def self.search_event(sport, start_date, end_date, party_size, location, radius)

  #   #search by sports
  #   if sport == "All sports"
  #     search_by_sports = []
  #     Event.all.each { |event| event.active? ? search_by_sports << event : 5}
  #   else
  #     sports = Sport.where(name: sport)
  #     search_prelim = Event.where(sport: sports)
  #     search_by_sports = []
  #     search_prelim.each {|event| event.active? ? search_by_sports << event : 5}
  #   end

  #   #search by dates

  #   if (start_date.nil? || end_date.nil?)
  #     search_by_sports_dates = search_by_sports
  #   else
  #     unless (start_date.empty? || end_date.empty?) ||
  #       search_by_sports_dates = []
  #       search_by_sports.each { |event| event.dates?(start_date, end_date) ? search_by_sports_dates << event : 5}
  #     else
  #       search_by_sports_dates = search_by_sports
  #     end
  #   end

  #   if party_size == "Party size"
  #     search_by_sports_dates_party = []
  #     search_by_sports_dates.each {|event| event.available? ? search_by_sports_dates_party << event : 5 }
  #   else
  #     search_by_sports_dates_party = []
  #     search_by_sports_dates.each { |event| party_size.to_i <= event.missing_player ? search_by_sports_dates_party << event : 5 }
  #   end

  #   if (location.nil? || radius.nil?)
  #     search_by_sports_dates_party_location = search_by_sports_dates_party
  #   else
  #     unless location.empty? || radius.empty?
  #       search_by_sports_dates_party_location = []
  #       Event.near(location, radius).each do |event|
  #         search_by_sports_dates_party_location << event if search_by_sports_dates_party.include?(event)
  #       end
  #     else
  #       search_by_sports_dates_party_location = search_by_sports_dates_party
  #     end
  #   end


  #   return search_by_sports_dates_party_location
  # end

  def dates?(start_date, end_date)
    ((start_date <= self.start) && (self.start <= end_date)) && ((start_date <= self.end) && (self.end <= end_date))
  end

  def available?
    self.missing_player > 0
  end

  def update_players
    self.bookings.each { |booking| self.missing_player -= booking.no_players}
    self.save
  end

  def active?
    self.active
  end

  def distance_from(searcher_coords)
    Geocoder::Calculations.distance_between([self.latitude, self.longitude], searcher_coords)
  end

  def self.distance_from_sorted(searcher_coords)
    all.sort_by { |e| e.distance_from(searcher_coords) }
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy, :protected]
  before_action :set_event, only: [:edit, :update, :destroy, :show, :protected, :create_players]
  before_action :create_players, only: [:update]
  skip_after_action :verify_policy_scoped, only: :index

  def index
# This is the search
# Overall list
    @events = Event.all
    @events = @events.where("active = true")
# by location
    @events = @events.near(params[:location], params[:radius]) if params[:location].present? && params[:radius].present?
# by time
    @events = @events.where(['start_time >= ? and end_time <= ?', DateTime.parse(params[:start_time]), DateTime.parse(params[:end_time])]) if params[:start_time].present? && params[:end_time].present?
# by sports
    @events = @events.joins(:sport).where(sports: { name: params[:sports] }) if params[:sports].present? && Sport.all.map(&:name).include?(params[:sports][0])
# by spaces
    @events = @events.where('missing_player >= ?', params[:missing_player]) if params[:missing_player].present?
    @events = @events.where('missing_player > 0')
# by vibe
    @events = @events.where(level: params[:event_vibe]) if params[:event_vibe].present?
# by type
    @events = @events.where(gender: params[:event_type]) if params[:event_type].present?
# by friends
    if user_signed_in?
      friend_events = []
      @events.all.each { |event| event.players.each { |player| friend_events << event if current_user.friend_uids.include?(player.user.uid) } }
      @events = friend_events.uniq if params[:friends_radio] && params[:friends_radio] == "friends"
    end

    @sports_list = Event.all.map { |event| event.sport.name }.uniq
    @searcher_coordinates = Geocoder.coordinates(params[:location])

    # Sorting
    case params[:sort]
    when 'distance'
      @events = @events.distance_from_sorted @searcher_coordinates
    else
      @events = @events.reorder((params[:sort].to_sym || :start_time) => (params[:order].to_sym || :desc)) if params[:sort].present?
    end
    # Old search keep for reference
    # @events = Event.search_event(params[:sports], params[:start], params[:end], params[:missing_player], params[:location], params[:radius])

    @hash = Gmaps4rails.build_markers(@events) do |event, marker|
      marker.lat event.latitude
      marker.lng event.longitude
    end
  end

  # create a new event
  def new
    @event = Event.new
    authorize @event
  end

  # perform create action
  def create
    @event = Event.create(event_params.except(:player_ids))
    authorize @event
    create_players

    # Create players using @event and selected user(s)
    @event.user = current_user
    if @event.save
      redirect_to event_path(@event)
    else
      render :new
    end
  end

  # display particular event
  def show
    @booking = Booking.new
    # authorize @booking

    @events = [@event]
    @hash = Gmaps4rails.build_markers(@events) do |event, marker|
      marker.lat event.latitude
      marker.lng event.longitude
      # marker.infowindow render_to_string(partial: "/flats/map_box", locals: { flat: flat })
    end
  end

  def protected
    redirect_to @event
  end

  # edit event details
  def edit
  end

  def update
    # params[:event][:player_ids] = @players
    if @event.update(event_params.except(:player_ids))
      redirect_to event_path(@event)
    else
      render :new
    end
  end


  def destroy
    @event.update(active: false)
    redirect_to events_path
  end

  private

  def create_players
    # User.where("username = ?", event_params[:player_ids][1])
    @event.players.destroy_all
    params[:event][:player_ids].each do |username|
      if username.present?
        working_user = User.where("username = ?", username).first
        @event.players << Player.create!(event: @event, user: working_user)
      end
    end
    # params[:event][:player_ids] = @players
  end

  def set_event
    @event = Event.find(params[:id])
    @users = User.all
    authorize @event
  end

  def event_params
    params.require(:event).permit(:title, :user_id, :description, :postcode, :sport_id, :start_time, :end_time, :missing_player, :requirements, :level, :address, :city, :country, :venue_name, :gender, player_ids: [])
  end

end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_banner.html.erb
<div style="background-image: url(<%= image_path "sports-photos/#{@event.sport.name}.jpg" %>); width: 100%; background-size: cover; height: 25vh; background-position: top;">
  <div class="container text-center">
     <div class="row">
      <div class="col-xs-12">
        <h1 style="padding-top: 6vh; font-size: 50px; color: $brand-color">
          <%= @event.title %> | <%= @event.sport.name %>
        </h1>
      </div>
    </div>
  </div>
</div>

app/views/events/_card.html.erb
<% if booking.user.photo %>
<% avatar_url = booking.user.photo.path %>
<% elsif booking.user.facebook_picture_url %>
<% avatar_url = booking.user.facebook_picture_url.gsub("square", "large") %>
<% else %>
<% avatar_url = "https://api.adorable.io/avatars/285/sportl.png" %>
<% end %>

<div class="profile-card" style="margin:0">

  <div class="front">
    <div class="background">

      <div class="profile-card-header">
        <div class="profile-card-avatar">
          <%= cl_image_tag avatar_url, class: "avatar-large text-center" %>
        </div>
      </div>

      <div class="profile-card-body">
        <h3><%= booking.user.first_name %></h3>
        <p>wants to join:</p>
        <div class="match-details">
          <div class="sport-image">
            <%= image_tag ("sports/" + booking.event.sport.name + ".png"), style: "width: 4vmin" %>
            <p><%= booking.event.title %></p>
          </div>
          <div class="on">
          <p>on</p>
          </div>
          <div class="sport-time">
            <p><%= booking.event.start_time.strftime("%e %B %Y") %></p>
            <p><%= booking.event.start_time.strftime("%y:%S") %></p>
          </div>
        </div> <!-- end of match-details -->
      </div> <!-- end of body -->

    </div> <!-- end of background -->
  </div> <!-- end of front -->

  <div class="back">
    <div class="background">

      <div class="profile-card-header">
        <div class="profile-card-avatar">
          <%= link_to profile_path(booking.user) do %>
            <%= cl_image_tag avatar_url, class: "avatar-large text-center"%>
          <% end %>
        </div>
      </div>

      <div class="profile-card-body">
        <h3><%= booking.user.first_name %></h3>
        <% if booking.user.bio? %>
          <p><%= booking.user.bio.truncate_words(10) %></p>
        <% else %>
          <p>no bio</p>
        <% end %>

        <div class="match-details">
          <% if booking.pending? %>
            <div class="accept-btn">
              <%= simple_form_for(booking) do |f| %>
                <%= f.hidden_field :booking_state, value: 1 %>
                <%= f.button :submit, "Accept", class: "btn accept-btn" %>
              <% end %>
            </div>
            <div class="deny-btn">
              <%= simple_form_for(booking) do |f| %>
                <%= f.hidden_field :booking_state, value: 2 %>
                <%= f.button :submit, "Deny", class: "btn deny-btn" %>
              <% end %>
            </div>
            <% elsif booking.accepted? %>
              <div class="accepted-sign">
                <p class="text-center">Accepted</p>
              </div>
            <% elsif booking.denied? %>
              <div class="denied-sign">
                <p class="text-center">Denied</p>
              </div>
          <% end %>
        </div> <!-- end of match details -->
      </div> <!-- end of profile card body -->

    </div> <!-- end of background -->
  </div> <!-- end of back -->

</div> <!-- end of whole card -->

app/views/events/_event_owner.html.erb
<!-- details -->

<div class="large-page-container">

  <!-- GAME DETAILS -->

  <div class="grey-container">
    <h3 class="text-center">GAME DETAILS</h3>
    <div class="row"> <!-- beginning of main content -->

      <div class="col-sm-8"> <!-- left side of main -->
        <div class="row"> <!-- left side (requests) -->

          <% if @event.bookings.where(booking_state: 0).any? %>
            <div class="col-sm-12">
              <div class="white-box">
                <div class="row">
                  <h5 class="text-center" style="padding-bottom: 5px">PENDING BOOKINGS</h5>
                  <% @event.bookings.where(booking_state: 0).each do |booking| %>
                    <div class="col-sm-4">
                      <%= render 'card', booking: booking %>
                    </div>
                  <% end %>
                </div>
              </div>
            </div>
          <% else %>
            <div class="col-sm-12">
              <div class="white-box">
                <h5 class="text-center"> No Pending Bookings!</h5>
              </div>
            </div>
          <% end %>

        </div> <!-- end of row (requests to join) -->

        <div class="row">
          <div class="col-sm-12">
            <div class="white-box">
              <h5 class="text-center">ACCEPTED REQUESTS</h5>
              <div class="flex-space-around">
                <% @event.bookings.where(booking_state: 1).each do |booking| %>
                  <% if booking.user.photo %>
                    <% avatar_url = booking.user.photo.path %>
                  <% elsif booking.user.facebook_picture_url %>
                    <% avatar_url = booking.user.facebook_picture_url.gsub("square", "large") %>
                  <% else %>
                    <% avatar_url = "https://api.adorable.io/avatars/285/sportl.png" %>
                  <% end %>
                  <p> <%= cl_image_tag avatar_url, class: "avatar-large" %> <%= link_to (booking.user.username? ? booking.user.username : booking.user.email), profile_path(booking.user) %>
                  <%= link_to chat_rooms_path(sender_id: current_user.id, recipient_id: booking.user.id), method: "post" do %>
                    <i class="fa fa-commenting"></i>
                  <% end %>
                  </p>
                <% end %>
              </div>
            </div>
          </div>
        </div>

      </div> <!-- end of left main col-md-8 -->

      <!-- EVENT DETAILS -->
      <div class="col-sm-4">
        <div class="flex-container-column white-box">
          <h5 class="text-center">VIBE</h5>
          <p class="text-center">
            <%= Event::LEVELS[@event.level - 1].humanize %>
          </p>
          <h5 class="text-center">PLAYERS NEEDED</h5>
          <p class="text-center">
            <% @event.missing_player.times do %>
              <i class="fa fa-user colour-icon" aria-hidden="true"></i>
            <% end %>
          </p>
          <h5 class="text-center">TYPE</h5>
          <p class="text-center">
            <% if @event.gender.downcase == "female" %>
              <i class="fa fa-venus colour-icon"></i> ladies
            <% elsif @event.gender.downcase == "male" %>
              <i class="fa fa-mars colour-icon"></i> mens
            <% else %>
              mixed
            <% end %>
          </p>
        </div> <!-- end of flex-container-column -->

        <!-- EXTRA INFO -->
        <div class="flex-container-column white-box">
          <h5 class="text-center">DETAILS</h5>
          <div class="flex-space-between">
            <p><i class="fa fa-calendar"></i></p>
            <p>
              <% if @event.start_time.to_date == @event.end_time.to_date %>
                <%= @event.start_time.strftime("%A %d %B") %>
              <% else %>
                <%= @event.start_time.strftime("%A %d %B") %> - <%= @event.end_time.strftime("%A %d %B") %>
              <% end %>
            </p>
          </div>
           <div class="flex-space-between">
            <p><i class="fa fa-clock-o"></i></p>
            <p>
              <% if @event.start_time.to_date == @event.end_time.to_date %>
                <%= @event.start_time.strftime("%H:%M") %> - <%= @event.end_time.strftime("%H:%M") %>
              <% else %>
                <%= @event.start_time.strftime("%H:%M") %> <span class="grey-text">(<%= @event.start_time.strftime("%A %d") %>)</span> - <%= @event.end_time.strftime("%H:%M") %> <span class="grey-text">(<%= @event.end_time.strftime("%A %d") %>)</span>
              <% end %>
            </p>
          </div>
          <div class="flex-space-between">
            <p><i class="fa fa-suitcase"></i></p>
            <p>
              <% if @event.requirements == "" || @event.requirements.nil? %>
                  no kit needed
              <% else %>
                <%= @event.requirements %>
              <% end %>
            </p>
          </div>

        </div> <!-- end of flex-container-column -->

        <div class="flex-container-column white-box">
          <h5 class="text-center">DESCRIPTION</h5>
          <p><%= @event.description %></p>
        </div>
      </div> <!-- end of col-md-4 (right-side details) -->
    </div> <!-- end of main row -->
  </div> <!-- end of grey-container -->
</div> <!-- end of page/container -->

 <script>
  <% content_for(:after_js) do %>
    <%= javascript_tag do %>
      $(document).on('ready', function() {
        $(".profile-card").flip();
        var handler = Gmaps.build('Google');
        handler.buildMap({ internal: { id: 'map' } }, function(){

         <% @hash = Gmaps4rails.build_markers(@event) do |event, marker| %>
           markers = handler.addMarkers([
               {
                 lat: <%= event.latitude %>,
                 lng: <%= event.longitude %>,
                 picture: {
                   url: "<%= image_path ("sports/thumbnails/" + event.sport.name + ".png") %>",
                   width:  50,
                   height: 50
                 }
               }
             ]);
           <% end %>

         markers.forEach(function(marker) {
           handler.bounds.extendWith(marker);
         });
         handler.fitMapToBounds();
        handler.getMap().setZoom(14);
       });
      })
    <% end %>
  <% end %>
</script>

app/views/events/edit.html.erb
<%= render "form" %>

app/views/events/new.html.erb
<%= render "form" %>

app/views/events/show.html.erb
<!-- banner -->
<div class="show-banner text-center" style="background-image: linear-gradient(-225deg, rgba(0, 0, 0, 0.4) 0%, rgba(0, 0, 0, 0.4) 50%), url(<%= image_path "sports-photos/#{@event.sport.name}.jpg" %>); width: 100%; background-size: cover; height: 50vh; background-position: center;">
  <div class="show-banner-content">
    <h1>
      <span class="banner-event-title"> <%= @event.title %> | </span>
      <span class="banner-sport-name"> <%= @event.sport.name %> </span>
    </h1>
    <% if user_signed_in? %>
      <%= render 'bookings/form' unless @event.user.id == current_user.id %>
      <% if current_user == @event.user %>
        <div class="edit-delete">
          <%= link_to edit_event_path(@event) do %>
            <i class="fa fa-pencil fa-2x" aria-hidden="true"></i>
          <% end %>
          <%= link_to @event, method: :delete, data: { confirm: 'Are you sure?' } do%>
            <i class="fa fa-trash-o fa-2x" aria-hidden="true"></i>
          <% end %>
        </div>
      <% end %>
    <% else %>
      <%= render 'bookings/form' %>
    <% end %>
  </div>
</div>

<% if user_signed_in? %>
  <% if @event.user.id == current_user.id %>
    <%= render 'event_owner' %>
  <% else %>
    <%= render 'event_viewer'%>
  <% end %>
<% else %>
  <%= render 'event_viewer'%>
<% end %>

app/views/events/spare_owner.html.erb
<div class="container">

  <div class="row">
  <div class="col-xs-4">
    <h2> Key information </h2>
          <h3>Time:</h3>
      <p>
        <% if @event.start_time.to_date == @event.end_time.to_date %>
          <%= @event.start_time.strftime("%A %d %B") %>
        <% else %>
          <%= @event.start_time.strftime("%A %d %B") %> - <%= @event.end_time.strftime("%A %d %B") %>
        <% end %>

          from

        <% if @event.start_time.to_date == @event.end_time.to_date %>
          <%= @event.start_time.strftime("%H:%M") %> to <%= @event.end_time.strftime("%H:%M") %>
        <% else %>
          <%= @event.start_time.strftime("%H:%M") %> <span class="grey-text">(<%= @event.start_time.strftime("%A %d") %>)</span> to <%= @event.end_time.strftime("%H:%M") %> <span class="grey-text">(<%= @event.end_time.strftime("%A %d") %>)</span>
        <% end %>
      </p>
      <h3> Players accepted:</h3>
          <% @event.bookings.where(booking_state: 1).each do |booking| %>
            <p> <%= link_to (booking.user.username? ? booking.user.username : booking.user.email), profile_path(booking.user) %>
              <%= link_to chat_rooms_path(sender_id: current_user.id, recipient_id: booking.user.id), method: "post" do %>
               <i class="fa fa-commenting"></i>
              <% end %>

             </p>
            <% end %>


                <h3>Players needed:
            <% @event.missing_player.times do %>
              <i class="fa fa-user colour-icon" aria-hidden="true"></i>
            <% end %>
          </h3>
  </div>

<div class="col-xs-8">
  <!-- loop through booking requests -->
<% if @event.bookings.where(booking_state: 0).any? %>
  <h1 class="text-center"> Pending Bookings!</h1>
    <% @event.bookings.where(booking_state: 0).each do |booking| %>
    <!-- set image of person requesting a place -->


      <div class="col-xs-4">
      <!-- start of profile card -->
      <%= render 'card', booking: booking%>

        </div>
    <% end %>
  <% else %>
  <h1 class="text-center"> No Pending Bookings!</h1>
  <% end %>
  </div>
  </div>
</div>


<% content_for(:after_js) do %>
   <script>
   $(document).ready(function(){
    $(".profile-card").flip();
   });
   </script>
<% end %>

app/views/events/spare_show.html.erb
<!-- banner -->
<div class="show-banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url(<%= image_path "sports-photos/#{@event.sport.name}.jpg" %>); width: 100%; background-size: cover; height: 50vh; background-position: center;">
  <div class="container text-center">
    <h1 style="padding-top: 10vh; font-size: 50px">
      <span class="banner-event-title"> <%= @event.title %> | </span>
      <span class="banner-sport-name"> <%= @event.sport.name %> </span>
    </h1>
  </div>
  <div class="edit-delete">
    <%= link_to edit_event_path(@event) do %>
      <i class="fa fa-pencil fa-2x" aria-hidden="true"></i>
    <% end %>
    <%= link_to @event, method: :delete, data: { confirm: 'Are you sure?' } do%>
      <i class="fa fa-trash-o fa-2x" aria-hidden="true"></i>
    <% end %>
  </div>
</div>

<!-- details -->
<div class="container">
  <div class="row">
    <!-- buttons -->
    <div class="col-xs-8 col-xs-offset-2">
      <div class="buttons-show">
        <div class="col-xs-8">
          <div class="booking-button-show text-center">
            <%= render 'bookings/form' %>
          </div>
        </div>
        <div class="col-xs-4">
          <div class="chat-button-show text-center">
            <%= link_to "Chat to Event owner", chat_rooms_path(sender_id: current_user.id, recipient_id: @event.user.id), method: :post, class: "btn btn-success btn-lg" %>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-12 col-md-8">
      <div class="row">
        <div class="col-xs-6">
          <h3>Level:
            <% @event.level.times do %>
              <i class="fa fa-square colour-icon" aria-hidden="true"></i>
            <% end %>
            <% (5 - @event.level).times do %>
              <i class="fa fa-square-o colour-icon" aria-hidden="true"></i>
            <% end %>
          </h3>
        </div>
        <div class="col-xs-6">
          <h3>Players needed:
            <% @event.missing_player.times do %>
              <i class="fa fa-user colour-icon" aria-hidden="true"></i>
            <% end %>
          </h3>
        </div>
      </div>
      <h3>Date:</h3>
      <p>
        <% if @event.start_time.to_date == @event.end_time.to_date %>
          <%= @event.start_time.strftime("%A %d %B") %>
        <% else %>
          <%= @event.start_time.strftime("%A %d %B") %> - <%= @event.end_time.strftime("%A %d %B") %>
        <% end %>
      </p>
      <h3>Time:</h3>
        <% if @event.start_time.to_date == @event.end_time.to_date %>
          <%= @event.start_time.strftime("%H:%M") %> - <%= @event.end_time.strftime("%H:%M") %>
        <% else %>
          <%= @event.start_time.strftime("%H:%M") %> <span class="grey-text">(<%= @event.start_time.strftime("%A %d") %>)</span> - <%= @event.end_time.strftime("%H:%M") %> <span class="grey-text">(<%= @event.end_time.strftime("%A %d") %>)</span>
        <% end %>
      <h3>Description:</h3>
      <p><%= @event.description %></p>
      <h3>Kit requirements:</h3>
      <% if @event.requirements == "" %>
        None
      <% else %>
        <p><%= @event.requirements %></p>
      <% end %>
    </div>
<!-- map -->
    <div class="col-xs-12 col-md-4">
      <h3>Location:</h3>
      <p><%= @event.venue_name %></p>
      <p><%= @event.full_address %></p>
      <div id="map5" style="width: 100%; height: 375px;"></div>

      <% if @event.players.length > 0 %>
        <ul class="list-inline">
          <h3>People going:</h3>
          <% @event.players.each do |player| %>
            <li style="margin-bottom: 15px;">
              <% if !player.user.photo %>
                <% profile_image = "https://api.adorable.io/avatars/285/sportl.png" %>
              <% else %>
                <% profile_image = player.user.photo.path || player.user.facebook_picture_url.gsub("square", "large") %>
              <% end %>
              <%= link_to profile_path(player.user), style: "text-decoration: none;" do %>
                <%= cl_image_tag profile_image, max_width: 200, crop: :fill, responsive_placeholder: "blank", class: "avatar-large" %>
                <%= player.user.username %>
              <% end %>
            </li>
          <% end %>
        </ul>
      <% end %>

    </div>
  </div>
  <div class="row">
    <h3>Captain:</h3>
    <div class="col-xs-5 col-md-2 col-lg-2">
      <div class="captain-face">
        <% avatar_url = @event.user.photo? ? cl_image_path(@event.user.photo.path) : @event.user.facebook_picture_url || "https://api.adorable.io/avatars/285/sportl.png" %>
        <%= image_tag avatar_url, class: "avatar-xlarge" %>
      </div>
    </div>
    <div class="col-xs-7 col-md-3 col-lg-2">
      <div class="captain-name">
        <h4><%= @event.user.first_name %> ( <%= @event.user.username %>)</h4>
        <p><%= @event.user.created_at.strftime("Joined in %B, %Y") %></p>
      <p> Sportl events captained: <%= @event.user.events.count %> </p>
      </div>
    </div>
    <div class="col-xs-12 col-md-7 col-lg-8">
      <p> <%= @event.user.bio %> </p>
    </div>
  </div>
</div>


 <script>
  <% content_for(:after_js) do %>
    <%= javascript_tag do %>
      $(document).on('ready', function() {
        var handler = Gmaps.build('Google');
        handler.buildMap({ internal: { id: 'map5' } }, function(){

         <% @hash = Gmaps4rails.build_markers(@event) do |event, marker| %>
           markers = handler.addMarkers([
               {
                 lat: <%= event.latitude %>,
                 lng: <%= event.longitude %>,
                 picture: {
                   url: "<%= image_path ("sports/thumbnails/" + event.sport.name + ".png") %>",
                   width:  50,
                   height: 50
                 }
               }
             ]);
           <% end %>

         markers.forEach(function(marker) {
           handler.bounds.extendWith(marker);
         });
         handler.fitMapToBounds();
        handler.getMap().setZoom(14);
       });
      });
    <% end %>
  <% end %>
</script>